### ISSUE TITLE
sqlalchemy.exc.CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause (SQL Server 2022)

### ISSUE THREAD

**Issue by andez2000** [gramener/gramex#672] opened 2023-01-03 14:00 UTC
I am seeing the error `sqlalchemy.exc.CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause` in the console when I perform a FastAPI request to pull data from the database.  

**Steps to reproduce.**
I am using the following code to pull data from my database (search + paging):

```python
@router.get("/")
def get_all(db: Session = Depends(get_db), limit: int = 10, page: int = 1, search: str = ''):
    skip = (page - 1) * limit
    foos = db.query(models.Foo) \
        .filter(models.Foo.name.contains(search)) \
        .limit(limit) \
        .offset(skip) \
        .all()
    return {'status': 'success', 'results': len(foos), 'foos': foos}
```

I am calling this from url `http://127.0.0.1:8000/api/foos/` - therefore:
`limit` is 10  
`page` is 1
`search` is ''

**Expected behavior:**
I was expecting it to return my 3 foos that I have in the database.

**Your environment:**

OS: Windows 10
Python version: 3.10.7
SQL Server: Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) (Hypervisor) 

__requirements.txt__

```
fastapi==0.88.0
...
pydantic==1.10.4
pyodbc==4.0.35
...
SQLAlchemy==1.4.45
```

__connection string__

`DATABASE_URI = f"mssql+pyodbc://local_test:local_test@localhost:1433/foo.db?driver=ODBC+Driver+17+for+SQL+Server"`

**Comment by sanand0** [comment] 2023-01-03 14:06
This is a duplicate of #626 which will be fixed in Gramex 1.87 to be released tomorrow. Thanks for raising, @andez2000

**Comment by andez2000** [comment] 2023-01-03 14:27
Sorry - is the bug itself is buried in SQL Alchemy library?

**Comment by sanand0** [comment] 2023-01-10 08:20
@andez2000, took me a while to trace it, but yes, it's part of the [SQLAlchemy library](https://github.com/sqlalchemy/sqlalchemy/blob/5147bf8e3cb321b8728b3af5bb0b2644995b3793/lib/sqlalchemy/dialects/mssql/base.py#L2089-L2097).

It doesn't look like a bug, though. More a requirement by the database MS SQL itself, to sort rows explicitly if we use OFFSET or LIMIT.

We've worked around this in Gramex 1.87 by sorting based on the first sortable column if no sort is specified.

**Closed by sanand0** 2023-01-10 08:20 UTC
