### ISSUE TITLE
logviewer post transformations are throwing errors

### ISSUE THREAD

**Issue by naveenreddymanukonda** [gramener/gramex#280] opened 2020-09-03 06:42 UTC
Using post transformations we created new columns in logviewer.db. After a day or two, it is throwing the below error saying that column doesn't exist in DB.

![image](https://user-images.githubusercontent.com/40488776/92080143-abdafe80-edde-11ea-979d-9a34d490ea6e.png)

**Comment by pratapvardhan** [comment] 2020-09-03 11:58
@naveenreddymanukonda -- could you please share a detailed log for this, which would identify the line in logviewer.py that's causing the error?

**Comment by naveenreddymanukonda** [comment] 2020-09-03 12:05
Traceback (most recent call last):
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/gramex/handlers/formhandler.py", line 153, in get
    result[key] = yield val
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/gramener/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/gramener/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/gramener/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/gramex/data.py", line 234, in filter
    data = gramex.cache.query(text(query), engine, state, params=all_params)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/gramex/cache.py", line 454, in query
    result = pd.read_sql(sql, engine, **kwargs)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/pandas/io/sql.py", line 436, in read_sql
    chunksize=chunksize,
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/pandas/io/sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/pandas/io/sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2166, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: aggD
[SQL: SELECT date(time) as date, count(status) as value FROM aggD where status in ('400 Bad Request','404 Not Found','500 Internal Server Error') and date(time) between '2020-08-04' and '2020-09-03' and device = Device and location = Location and language = Language and (uri like '%/jsi%' or uri like '%graphics-gallery' or uri like '%about' or uri like '/profile%' or uri like '/' or uri like '%visualize' or uri like '%datasets-page' or uri like '/workshop?%' or uri like '%idp-mobile/jsi' or uri like '%idp-mobile/graphics-gallery' or uri like '%idp-mobile/about' or uri like '%idp-mobile/datasets-page' or uri like '%idp-mobile/profile' or uri like '%idp-mobile/workshop%') and "user.id" != '-' group by date(time)]
(Background on this error at: http://sqlalche.me/e/e3q8)
ERROR   03-Sep 11:43:51 formhandler 9991 idp-log-viewer-data: filter failed
Traceback (most recent call last):
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: aggD

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/gramex/handlers/formhandler.py", line 153, in get
    result[key] = yield val
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/gramener/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/gramener/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/gramener/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/gramex/data.py", line 234, in filter
    data = gramex.cache.query(text(query), engine, state, params=all_params)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/gramex/cache.py", line 454, in query
    result = pd.read_sql(sql, engine, **kwargs)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/pandas/io/sql.py", line 436, in read_sql
    chunksize=chunksize,
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/pandas/io/sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/pandas/io/sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2166, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: aggD
[SQL: select count(uri) as value, uri as urls, date(time) as date from aggD where (uri LIKE '%/storelogs?dataset_downloads=%' or uri LIKE '%/idp-mobile/storelogs?capture_image%') AND status = '200 OK' and date(time) between '2020-08-04' and '2020-09-03' and device = Device and location = Location and language = Language group by date(time)]
(Background on this error at: http://sqlalche.me/e/e3q8)
ERROR   03-Sep 11:43:52 formhandler 9991 idp-log-viewer-data: filter failed
Traceback (most recent call last):
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/gramener/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: aggD

The above exception was the direct cause of the following exception:

**Comment by pratapvardhan** [comment] 2020-09-03 12:11
@naveenreddymanukonda -- errors are different, earlier was about missing column. This one is about no such table? Former probably happens during the scheduled job run, later is when query is run (from dashboard). We want to identify cause for former issue in this I suppose?

**Comment by pratapvardhan** [comment] 2020-09-04 12:55
Likely caused by having two separate instances of gramex running different logviewer and log configuarion but writing data to same place caused this. Also, scheduler was running at the same time for these. @naveenreddymanukonda is now aware this, and will make necessary changes.

**Comment by sanand0** [comment] 2020-09-08 03:34
@naveenreddymanukonda -- since this is resolved, could you please share how you and @pratapvardhan solved it? Then close the issue?

**Comment by naveenreddymanukonda** [comment] 2020-09-08 04:45
Thanks, @pratapvardhan for helping resolve this issue.

We are running multiple gramex instances in the production server each instance which starts the log viewer on each port, which should be avoided log viewer should only run on one port even we are running multiple gramex instances. This can be resolved by specifying the port in the log viewer definition. Please see the sample snippet below.

```
logviewer:
    path: $GRAMEXAPPS/logviewer/gramex.yaml
    YAMLURL: $YAMLURL/log/
    LOGVIEWER_SCHEDULER_PORT: '<Port Number>'  ##Sepcify one port to run the logviewer when running multiple gramex instances
```

**Comment by sanand0** [comment] 2020-09-14 06:53
Reopened for documentation.

I will add documentation to https://learn.gramener.com/guide/logviewer/ and then close this issue.

**Comment by sanand0** [comment] 2020-09-29 06:36
Closed via https://github.com/gramener/gramex-guide/commit/fce57998fc0fbdf963c0f1df2f32a415c81dae0e

**Closed by sanand0** 2020-09-29 06:36 UTC
Labels: logging
