### ISSUE TITLE
bootstrap-select version upgrade

### ISSUE THREAD

**Issue by PragnyaReddy** [gramener/gramex#138] opened 2019-03-25 08:15 UTC
Current version of bootstrap-select in UI Components throws DOMException (https://github.com/snapappointments/bootstrap-select/issues/2221). Needs to be upgraded to v1.13.7 or above.

**Comment by pratapvardhan** [comment] 2019-04-02 06:19
Opening due to regression in ab3c956 @sanand0

**Comment by sanand0** [comment] 2019-04-03 02:38
Very sorry! Fixed via 49ebdac

**Closed by sanand0** 2019-04-03 02:38 UTC
